plugins { id 'com.android.application' }

android { namespace 'com.saturnkuji.app'; compileSdk 35
    defaultConfig { applicationId 'com.saturnkuji.app'; minSdk 24; targetSdk 35; versionCode 9; versionName '9.0' }
    compileOptions { sourceCompatibility JavaVersion.VERSION_1_8; targetCompatibility JavaVersion.VERSION_1_8 }
}
